### ISSUE TITLE
Adding this song fails because the request does not send a videoId

### ISSUE THREAD

**Issue by NiklasRosenstein** [NiklasRosenstein/bbplay#15]
Searching for "droloe" and trying to play the first song (see screenshot) results in an error. Apparently the request does not send the videoId

![image](https://user-images.githubusercontent.com/1318438/70573334-0b82e100-1ba2-11ea-94ce-a59d4df0c77d.png)

**Comment by fewhnhouse** [comment]
we need the videoId - if its not there then we probably cant do anything with the song. Not sure how this can even be the case, the ID should always exist. For now i will just filter out the songs without videoID

**Comment by fewhnhouse** [comment]
Aaah okay yeah sure can do it in frontend 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by NiklasRosenstein** [comment]
Done it in the backend actually, I can search for just Videos with the YT API. Fixed by #34
