### ISSUE TITLE
Add restrictions for videos/songs which can be added to the playlist

### ISSUE THREAD

**Issue by JoNaSaanSan** [NiklasRosenstein/bbplay#22]
Limit the duration of videos/songs that can be added to 10 minutes.
Best case: Make videos not appear in the search list in the first place, if the video is longer than 10 minutes.

**Comment by fewhnhouse** [comment]
@NiklasRosenstein i guess you do this directly in your proxy?

**Comment by NiklasRosenstein** [comment]
We could do this three ways:

1. Don't even show YouTube videos in the search results that we wouldn't want users to play (YT search endpoint change + PUT track endpoint change)
2. Do not show the "Add to playlist" button for songs that we won't want users to play (UI change + PUT track endpoint change)
3. Just reject songs that we don't want to play with an error message (least effort as no UI change required)

**Comment by fewhnhouse** [comment]
I'd say def option 1, just limit it from the backend side 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
