### ISSUE TITLE
UI for adding one song to playlist for non-authenticated users

### ISSUE THREAD

**Issue by fewhnhouse** [NiklasRosenstein/bbplay#26]

**Comment by NiklasRosenstein** [comment]
Ah I was going to file this as well, and I thought right now it would be a bug. 😄 It could be the very same page that authenticated users currently view for the Playlist, only that it doesn't show all the elements for authenticated users (the Youtube player [can keep the bottom current track info though!] and the widgets to remove tracks [unless the user submitted the track themselves]).

**Comment by NiklasRosenstein** [comment]
This is already implemented by @fewhnhouse :)
